name: PSE Seminar Report
description: Manage creation of report
author: tarao1006
inputs:
  distribution_branch:
    description: Branch name used to distribute pdf
    required: true
    default: distribution
  report_filename:
    description: TeX file name
    required: true
    default: report.tex
  prefix:
    description: Directory name of seminar/%Y%m%d suffix
    required: true
    default: .
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: book
  color: gray-dark
